// <auto-generated />
namespace RiskTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Set_Empty_Demographics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_Empty_Demographics));
        
        string IMigrationMetadata.Id
        {
            get { return "201505132029332_Set_Empty_Demographics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
