// <auto-generated />
namespace RiskTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Outcomeframeworkrefs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Outcomeframeworkrefs));
        
        string IMigrationMetadata.Id
        {
            get { return "201508021112116_Outcome-framework-refs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
