// <auto-generated />
namespace RiskTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Project_Org_Application : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Project_Org_Application));
        
        string IMigrationMetadata.Id
        {
            get { return "201701092127081_Project_Org_Application"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
