// <auto-generated />
namespace RiskTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Riskdeletedflag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Riskdeletedflag));
        
        string IMigrationMetadata.Id
        {
            get { return "201703051434338_Risk-deleted-flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
