// <auto-generated />
namespace RiskTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RiskMap_Owning_Org : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RiskMap_Owning_Org));
        
        string IMigrationMetadata.Id
        {
            get { return "201701172253382_RiskMap_Owning_Org"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
